### ISSUE TITLE
Undetected forge mods

### ISSUE THREAD

**Issue by Gablers** [Aquerr/ClientInspector#2]
I'm currently hosting a "Pixelmon Reforged" server and using your plugin to stop hack mod/clients.

There's one : Pixelradar. It is unseeable in the console and is considered a hack.

I don't know how possible it'd be to try and detect it., but I'd love if it could be.   

- It's a bit of a ghost to find online, but I have the jar if you want to see it.

**Comment by Aquerr** [comment]
Hello! Thanks for you report.

I have already looked at it partially and I am not really sure yet how to handle it from the plugin. But, I will keep trying. Maybe I will find something useful for it.

Otherwise... I am thinking that a **client side mod** would be able to handle it. Such mod would have to be added to the modpack and be present on all clients which want to connect to the server. Furthermore, that mod would be communicating with the plugin on the server side and while connecting to the server, it would send **the real modlist** to the server.

**Comment by Gablers** [comment]
Thank you for the insight and work!

If I can help further just ask.

**Comment by Gablers** [comment]
Just a little idea: Would it be possible to read client-side config names?
It makes a client CFG file named "pixelradar" 

Just an idea, I don't know the ins and outs of modding so excuse if this is stupid!

**Comment by Aquerr** [comment]
I doubt it is possible to do it from the server. But I will check if it is possible. 

Also, I am planning to create ClientInspector mod that will be used on the client side and it will do the thing that I described above, that means, it will send the real mod list to the server.

Let’s leave this issue open so that I can post updates here.

**Comment by Aquerr** [comment]
It’s been a long time since last update here.

So, let’s get it started. 😄

I have just finished development of Client Inspector Forge mod. 

This mod will completely replace existing Sponge plugin.
It works almost the same like the plugin with one difference, that is, you have to install it on the client side.

The reason is that the server side needs to somehow ask the client side for installed mods. Because we need to send a special request packet to the client, we need to have a mod on the client side. Such mod will properly handle the request packet and will return us a mod list with all mods, even with those that are “hiding”. And that is what Client Inspector is doing.

Furthermore, the Client Inspector mod will be published both on Sponge and CurseForge and its dev release is already available at my discord server. I have also tested it already with the mod you mentioned in your message and it did properly send its name to the server.

Some extra thoughts:
I was thinking about having a possibility for having the mod installed only on the server side and letting the server owner to decide if they want to require Client Inspector on the client side but it does not seem worth. Firstly because you are not fully protected and normally as a server owner you would rather want full protection than half. And secondly, you are already making a mod pack and adding an additional mod on the client side will not make a big difference in the terms of performance but it will benefit in additional protection. Also, you will not need to worry about this mod when you are building separate packs for server (with additional plugins) and what for client (with client side only mods) as it will go to both packs.
